// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Spanner")>]
[<assembly: AssemblyProductAttribute("Spanner")>]
[<assembly: AssemblyDescriptionAttribute("Intervals for .NET")>]
[<assembly: AssemblyVersionAttribute("0.0")>]
[<assembly: AssemblyFileVersionAttribute("0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Spanner"
    let [<Literal>] AssemblyProduct = "Spanner"
    let [<Literal>] AssemblyDescription = "Intervals for .NET"
    let [<Literal>] AssemblyVersion = "0.0"
    let [<Literal>] AssemblyFileVersion = "0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
